#!/bin/bash

# Get the current layout
current_layout=$(setxkbmap -query | grep layout | awk '{print $2}')

# Toggle between cz and cz_custom
if [ "$current_layout" == "cz" ]; then
    setxkbmap us_qwertz   

else
    setxkbmap cz
fi
echo "WWWWWw"
